apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: iam-rbac-operator-aws-secrets
  namespace: devops-iam-rbac-autosyncs                                                            
spec:
  secretStoreRef:
    name: aws-cluster-secrets-store
    kind: ClusterSecretStore
  refreshInterval: 1m
  target:
    name: iam-rbac-operator-aws-secrets                                                                 
    creationPolicy: Owner
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: dev/test-eks/iam-rbac-autosyncs/iam-rbac-operator-aws-secrets
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_ACCESS_KEY
    remoteRef:
      key: dev/test-eks/iam-rbac-autosyncs/iam-rbac-operator-aws-secrets
      property: AWS_ACCESS_KEY
