---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: devops-iam-rbac-autosyncs
  name: iam-rbac-autosync-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iam-rbac-autosync-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [iamrbacautoupdater.com]
    resources: [clusteriamrbacautoupdaterpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch, get]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: [rolebindings]
    verbs: [list, watch, get, create]

  - apiGroups: [""]
    resources: [configmaps, events]
    verbs: [list, watch, get, patch, update, create]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [iamrbacautoupdater.com]
    resources: [iam-rbac-autosyncs]
    verbs: [list, watch, patch]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devops-iam-rbac-autosyncs
  name: iam-rbac-autosync-role-namespaced
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [iamrbacautoupdater.com]
    resources: [iamrbacautoupdaterpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [list, watch, patch, get, update, create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [iamrbacautoupdater.com]
    resources: [iam-rbac-autosyncs]
    verbs: [list, watch, patch]

  # Application: other resources it produces and manipulates.
  # Here, we create Jobs+PVCs+Pods, but we do not patch/update/delete them ever.
  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: [create]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iam-rbac-autosync-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iam-rbac-autosync-role-cluster
subjects:
  - kind: ServiceAccount
    name: iam-rbac-autosync-account
    namespace: devops-iam-rbac-autosyncs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: devops-iam-rbac-autosyncs
  name: iam-rbac-autosync-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iam-rbac-autosync-role-namespaced
subjects:
  - kind: ServiceAccount
    name: iam-rbac-autosync-account